### ISSUE TITLE
References to internal sap webservers in documentation

### ISSUE THREAD

**Issue by jonathanbaker7** [gardener/website#1]
I did a search of the project for "wdf.sap.corp" and found the following:

`<p>The Kubernetes clusters provided by <a href="https://github.wdf.sap.corp/pages/kubernetes/gardener/">Gardener</a> use role based
access control (<a href="https://kubernetes.io/docs/admin/authorization/rbac/">RBAC</a>). To authorize the Prometheus
node-exporter to access hardware and OS relevant metrics of your cluster&rsquo;s worker nodes specific artifacts need to be
deployed.</p>`

I suspect a reference was missed...

**Comment by jonathanbaker7** [comment]
Just FYI.  It happens in 5 places.  Here is the URL for the search:  https://github.com/gardener/website/search?q=wdf.sap.corp&unscoped_q=wdf.sap.corp

**Comment by freegroup** [comment]
thanks for the report.

We are currently in process to bring the internal project out to the external github.
We remove this asap.

I move the ticket to the https://github.com/gardener/documentation repo

greetings
